# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 487)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #800080, stop: 1 #0000FF);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #0000FF, stop: 1 #800080);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                                stop: 0 #800080, stop: 1 #0000FF);\n"
"    color: #800080;\n"
"}\n"
"")
        self.list_files = QtWidgets.QListWidget(MainWindow)
        self.list_files.setGeometry(QtCore.QRect(460, 120, 171, 351))
        self.list_files.setObjectName("list_files")
        self.btn_folder = QtWidgets.QPushButton(MainWindow)
        self.btn_folder.setGeometry(QtCore.QRect(460, 70, 171, 31))
        self.btn_folder.setObjectName("btn_folder")
        self.btn_save = QtWidgets.QPushButton(MainWindow)
        self.btn_save.setGeometry(QtCore.QRect(460, 30, 171, 31))
        self.btn_save.setObjectName("btn_save")
        self.image = QtWidgets.QLabel(MainWindow)
        self.image.setGeometry(QtCore.QRect(70, 50, 361, 161))
        self.image.setObjectName("image")
        self.transparency = QtWidgets.QLabel(MainWindow)
        self.transparency.setGeometry(QtCore.QRect(70, 50, 361, 161))
        self.transparency.setObjectName("transparency")
        self.transparency.setStyleSheet("font-size:40px;background-color: rgba(0,0,0,0.1);\
        border: 2px solid #222222")
        self.btn_smooth = QtWidgets.QPushButton(MainWindow)
        self.btn_smooth.setGeometry(QtCore.QRect(70, 400, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_smooth.setFont(font)
        self.btn_smooth.setObjectName("btn_smooth")
        self.btn_blur = QtWidgets.QPushButton(MainWindow)
        self.btn_blur.setGeometry(QtCore.QRect(160, 360, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_blur.setFont(font)
        self.btn_blur.setObjectName("btn_blur")
        self.btn_brightness = QtWidgets.QPushButton(MainWindow)
        self.btn_brightness.setGeometry(QtCore.QRect(160, 440, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_brightness.setFont(font)
        self.btn_brightness.setObjectName("btn_brightness")
        self.btn_saturation = QtWidgets.QPushButton(MainWindow)
        self.btn_saturation.setGeometry(QtCore.QRect(70, 440, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_saturation.setFont(font)
        self.btn_saturation.setObjectName("btn_saturation")
        self.btn_relief = QtWidgets.QPushButton(MainWindow)
        self.btn_relief.setGeometry(QtCore.QRect(160, 400, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_relief.setFont(font)
        self.btn_relief.setObjectName("btn_relief")
        self.btn_contrast = QtWidgets.QPushButton(MainWindow)
        self.btn_contrast.setGeometry(QtCore.QRect(250, 360, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_contrast.setFont(font)
        self.btn_contrast.setObjectName("btn_contrast")
        self.btn_enchamnet = QtWidgets.QPushButton(MainWindow)
        self.btn_enchamnet.setGeometry(QtCore.QRect(340, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_enchamnet.setFont(font)
        self.btn_enchamnet.setObjectName("btn_enchamnet")
        self.btn_boundaries = QtWidgets.QPushButton(MainWindow)
        self.btn_boundaries.setGeometry(QtCore.QRect(250, 400, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_boundaries.setFont(font)
        self.btn_boundaries.setObjectName("btn_boundaries")
        self.btn_doright = QtWidgets.QPushButton(MainWindow)
        self.btn_doright.setGeometry(QtCore.QRect(160, 320, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_doright.setFont(font)
        self.btn_doright.setObjectName("btn_doright")
        self.btn_mirror = QtWidgets.QPushButton(MainWindow)
        self.btn_mirror.setGeometry(QtCore.QRect(250, 320, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_mirror.setFont(font)
        self.btn_mirror.setObjectName("btn_mirror")
        self.btn_sharp = QtWidgets.QPushButton(MainWindow)
        self.btn_sharp.setGeometry(QtCore.QRect(340, 320, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_sharp.setFont(font)
        self.btn_sharp.setObjectName("btn_sharp")
        self.btn_doleft = QtWidgets.QPushButton(MainWindow)
        self.btn_doleft.setGeometry(QtCore.QRect(70, 320, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_doleft.setFont(font)
        self.btn_doleft.setObjectName("btn_doleft")
        self.btn_B_W = QtWidgets.QPushButton(MainWindow)
        self.btn_B_W.setGeometry(QtCore.QRect(70, 360, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_B_W.setFont(font)
        self.btn_B_W.setObjectName("btn_B_W")
        self.btn_invert = QtWidgets.QPushButton(MainWindow)
        self.btn_invert.setGeometry(QtCore.QRect(250, 440, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_invert.setFont(font)
        self.btn_invert.setObjectName("btn_invert")
        self.btn_path = QtWidgets.QPushButton(MainWindow)
        self.btn_path.setGeometry(QtCore.QRect(340, 360, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_path.setFont(font)
        self.btn_path.setObjectName("btn_path")
        self.btn_detal = QtWidgets.QPushButton(MainWindow)
        self.btn_detal.setGeometry(QtCore.QRect(340, 440, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_detal.setFont(font)
        self.btn_detal.setObjectName("btn_detal")
        self.sl_1red = QtWidgets.QSlider(MainWindow)
        self.sl_1red.setGeometry(QtCore.QRect(70, 210, 255, 22))
        self.sl_1red.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #8a2be2, stop:1 #4169e1);\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    width: 18px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"\n"
"}\n"
"")
        self.sl_1red.setOrientation(QtCore.Qt.Horizontal)
        self.sl_1red.setObjectName("sl_1red")
        self.sl_2green = QtWidgets.QSlider(MainWindow)
        self.sl_2green.setGeometry(QtCore.QRect(70, 240, 255, 22))
        self.sl_2green.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #8a2be2, stop:1 #4169e1);\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    width: 18px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"\n"
"}\n"
"")
        self.sl_2green.setOrientation(QtCore.Qt.Horizontal)
        self.sl_2green.setObjectName("sl_2green")
        self.sl_3blue = QtWidgets.QSlider(MainWindow)
        self.sl_3blue.setGeometry(QtCore.QRect(70, 270, 255, 22))
        self.sl_3blue.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #8a2be2, stop:1 #4169e1);\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    width: 18px;\n"
"    margin-top: -3px;\n"
"    margin-bottom: -3px;\n"
"\n"
"}\n"
"")
        self.sl_3blue.setOrientation(QtCore.Qt.Horizontal)
        self.sl_3blue.setObjectName("sl_3blue")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_folder.setText(_translate("MainWindow", "Папка"))
        self.btn_save.setText(_translate("MainWindow", "Збереження"))
        self.image.setText(_translate("MainWindow", "Картинка"))
        self.btn_smooth.setText(_translate("MainWindow", "Гладкий"))
        self.btn_blur.setText(_translate("MainWindow", "Блюр"))
        self.btn_brightness.setText(_translate("MainWindow", "Яскравість"))
        self.btn_saturation.setText(_translate("MainWindow", "Насиченість"))
        self.btn_relief.setText(_translate("MainWindow", "Рельєф"))
        self.btn_contrast.setText(_translate("MainWindow", "Контраст"))
        self.btn_enchamnet.setText(_translate("MainWindow", "П.К"))
        self.btn_boundaries.setText(_translate("MainWindow", "Границі"))
        self.btn_doright.setText(_translate("MainWindow", "Праворуч"))
        self.btn_mirror.setText(_translate("MainWindow", "Дзеркало"))
        self.btn_sharp.setText(_translate("MainWindow", "Різкість"))
        self.btn_doleft.setText(_translate("MainWindow", "Ліворуч"))
        self.btn_B_W.setText(_translate("MainWindow", "Ч/Б"))
        self.btn_invert.setText(_translate("MainWindow", "Інверт"))
        self.btn_path.setText(_translate("MainWindow", "Контур"))
        self.btn_detal.setText(_translate("MainWindow", "Деталі"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
